name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  issues:
    types: [opened]
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: jiajing1993/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 800497e9d8346efa4e561f8939f0d417
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
